### ISSUE TITLE
v0 User Research -- Assess and document partnering institution or PI interest and goals

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#11]
_As Product Owners, we want to make sure we have some cold-start partnering institutions or PIs to kickstart Moment usage. .

There has been a lot of interest in Moment from partnering institutions, PIs, and other potential Project Owners and Contributors (e.g. U of Toronto). These connections have been largely established early on, in 2022, and mostly through Ben B. 

Before we continue with development, we want to ensure that these potential partners are ready to user-test Moment and give us feedback on it. This would include bootstrapping the kickoff of Moment so we can observe real Project Owner-Contributor interactions and start building our base of users. Additionally, we want to make sure we know what their needs are as users and what they are most interested in using the platform for. 

Get a list of the partners from Ben B, ask him for any context he has, and then reach out to said partners for a user interview. Some questions could include:
- Would you be interested in trialing Moment in its early development? To what extent (Ie just give it a look over, use it in your workflows, be a primary partner, etc)?
- What would you like to see as an institution? Project Owner? Contributor?
- What features would make or break Moment for you?
- What about the current implementation works well for you? What does not?

# Assumptions:
1. Ben B has a list of the partners 
2. We can identify and reach out to these partners
3.  

# Acceptance Criteria
Given..., when..., then...

**Comment by ascourtas** [comment]
completed! Discussed with Noah, (someone else?), and consulted the US-RSE Guidebook. 

User interviews (internal): https://docs.google.com/document/d/1XTSAjnhYEtyL5JJgEHHExk2JiPqEmoH9fW3CElRNx6Q/edit?usp=sharing

US-RSE Guidebook: https://zenodo.org/records/8274378 

Final Moment project proposal as a result of this research can be found here (internal): https://docs.google.com/presentation/d/1mON2vLbIA5vo3IjO30bgZ_XXTl79dEmHqMdTEG-dTsE/edit?usp=sharing

**Comment by vladx2** [comment]
I didn't document this as we went along, but I feel like Ari and I have a common understanding about it. How about we circle back to it more formally after putting together the first cohort and document it then, to make sure we deliver on their exact needs?

**Comment by vladx2** [comment]
From Ari/Vlad sync: After we've got the project owners together we can send them an email.

**Comment by vladx2** [comment]
Superseded by https://github.com/Garden-AI/moment/issues/21
