### ISSUE TITLE
Design doc & review for Moment landing website

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#14]
This website would serve as a landing page/orientation tool for all things Moment. 

More info TBA

**Comment by vladx2** [comment]
I'll prioritise this doc this week, I just realised that it would be nice to have a central link for people to browse while we do outreach.

**Comment by ascourtas** [comment]
TODO: 

- [x] Ari to review doc 
- [x] Send doc out to larger team for comment

**Comment by ascourtas** [comment]
https://docs.google.com/document/d/10Ev3RwNU_JpbJpJH7VuklvB1iTbixbiAHV5MZejSPcc/edit
