### ISSUE TITLE
Add `help_text` for the Research Products form

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/moment#5]
Add `help_text` describing what the different fields mean on the Research Products form

**Comment by lodenrogue** [comment]
I saw your issue on Github's good first issue search. Where is the research products form where you want the change?

**Comment by ascourtas** [comment]
Hi @lodenrogue thanks for commenting, sorry for the delay there I was out on vacation. We're currently moving the code from another (private) repo to this one, but it's not completed just yet! Once it is though we can link to the form code :)
